### PR TITLE
Dark Mode Support

### LINKED ISSUE #15: Dark Mode Support
It'd be great if this theme supported the new CSS media query `prefers-color-scheme: dark`.

https://paulmillr.com/posts/using-dark-mode-in-css/

### PR DESCRIPTION
**Pull request by fishcharlie**
This PR closes #15.

This is a VERY first draft PR, I'd love input from @eibt on this. I'm not sure if the colors I used can be improved and made better, and there is probably more elements that need to be adjusted.

I have given maintainers push access to this PR/branch so it's easy to make commits to this PR before merging.

Please let me know how else I can support this effort.

### CODE REVIEW

**Comment by fishcharlie** [comment]
We might also want to update the README for this. Maybe have a section that talks about dark mode? And maybe have some of the images have half light mode and half dark mode?

One other thing we could look into, is a custom user toggle that allows for the following options:

- Automatic (uses `prefers-color-scheme` setting)
- Light mode (uses light mode despite `prefers-color-scheme` setting)
- Dark mode (uses dark mode despite `prefers-color-scheme` setting)

**Comment by eibt** [comment]
Quick update! Still testing it out! I'll have news soon! 👍

**Comment by fishcharlie** [comment]
Firefox 67 now has support for `prefers-color-scheme`, and Chrome 76 will be adding support for this (and it looks like that'll be released in July). iOS 13 added support for this media query, with the beta having been released to developers, public beta being released in July, and the official public release being released in the fall. And although I haven't confirmed this, it looks like Edge 76 will be adding support for this as well with their switch to Chromium in Edge 75.

So I'm guessing by the end of the year, this media query will have very mass adoption from browsers. That all being said, I think it'd be **great** to get this feature ready to stay on the cutting edge of this technology.

Design, color choices, and such are for sure a weak point for me. So although I tried to get a good start on this PR, I think it could be improved for sure. But I'd love to help as much as I possibly can, so @eibt please let me know what I can do to get this released! 😃

**Comment by eibt** [comment]
@fishcharlie That's awesome news! So I've been working on a separate theme that uses a dark color palette, maybe we can use the same colors (based on material design), here are some screenshots:

page not found

posts w- image

posts no image
Mesa de trabajo 15
Mesa de trabajo 13
Mesa de trabajo 17

**Comment by fishcharlie** [comment]
@eibt That looks super cool! Yeah I'm good with whatever. I just made this PR to try to get the ball rolling. But if there is a better solution, I'm all in. Just hoping to get dark mode support haha.

**Comment by eibt** [comment]
Sneak peak at the new Dark Mode, coming up on the next release!

localhost_html_(Laptop with HiDPI screen)
localhost_author_poetic-themes_page_2_(Laptop with HiDPI screen)
localhost_html_(iPhone 6_7_8 Plus) (1)
localhost_author_poetic-themes_page_2_(iPhone 6_7_8 Plus)
localhost_html_(iPhone 6_7_8 Plus)

Thanks to @fishcharlie for proposing this feature and contributing the starting code 👍

**Comment by eibt** [comment]
New Dark Mode in version 3! https://github.com/PoeticThemes/boo/releases/tag/v3.0

**Pull request closed without merging**
